name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_pref_annotation:
    path: ../shared_pref_annotation

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.1.2
  shared_pref_generator:
    path: ../shared_pref_generator


flutter:
  uses-material-design: true