name: shared_pref_generator
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  build: ^1.0.2
  source_gen: ^0.9.2
  shared_pref_annotation:
    path: ../shared_pref_annotation

dev_dependencies:
  build_runner: ^1.1.2
  
