name: pref_gen
description: Generator to create boilerplate for shared preferences based on a provided interface. The generator is platform agnostic README for more details
version: 0.0.3
authors:
  - Filip Grzywok <rj23@protonmail.com>
  - Gregory Sech <sech.gregory@gmail.com>
homepage: https://github.com/GregorySech/pref_gen

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  build: ^1.0.2
  source_gen: ^0.9.3
  code_builder: ^3.1.3
  pref_gen_annotations: ^0.0.1
  build_runner: ^1.1.2
  
